version: "3.9"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "${API_GATEWAY_PORT}:3000"
    mem_limit: 40m
    depends_on:
      - redis
      - rabbitmq
    environment:
      - PORT=3000
      - REDIS_URL=${REDIS_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - IDENTITY_SERVICE_URL=${IDENTITY_SERVICE_URL}
      - POST_SERVICE_URL=${POST_SERVICE_URL}
      - MEDIA_SERVICE_URL=${MEDIA_SERVICE_URL}
      - SEARCH_SERVICE_URL=${SEARCH_SERVICE_URL}
      - JWT_SECRET=${JWT_SECRET}

  identity-service:
    build: ./identity-service
    mem_limit: 60m
    depends_on:
      - redis
      - rabbitmq
    environment:
      - PORT=3001
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - JWT_SECRET=${JWT_SECRET}

  post-service:
    build: ./post-service
    mem_limit: 60m
    depends_on:
      - redis
      - rabbitmq
    environment:
      - PORT=3002
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}

  media-service:
    build: ./media-service
    mem_limit: 60m
    depends_on:
      - redis
      - rabbitmq
    environment:
      - PORT=3003
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}

  search-service:
    build: ./search-service
    mem_limit: 60m
    depends_on:
      - redis
      - rabbitmq
    environment:
      - PORT=3004
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}

  redis:
    image: redis:alpine
    mem_limit: 80m
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    mem_limit: 200m
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
